name: Go Build & Test
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'
      - '**.sql'
      - 'go.mod'
      - 'go.sum'
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build & Test
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'      

    - name: Remove windows dependencies for Ubuntu
      if: runner.os == 'Linux'
      run: |
        rm -r iphlpapi

    - name: GolangCI-Lint
      if: runner.os == 'Linux'
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --verbose

    - name: Get dependencies
      run: |
        go mod download
        go version
        go build

    # - name: Test
    #   run: go test -v -p 1 -coverprofile=profile.cov ./...

    # - name: Convert coverage to lcov
    #   uses: jandelgado/gcov2lcov-action@v1.0.2
    #   with:
    #       infile: profile.cov
    #       outfile: coverage.lcov

    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: coverage.lcov

    # - name: Run GoReleaser
    #   uses: goreleaser/goreleaser-action@master
    #   with:
    #     args: release --snapshot --skip-publish --rm-dist
